services:
  - type: web
    name: fishermantest
    env: docker
    repo: https://github.com/NGOhiroshi/metabase-render.git # optional
    plan: free # ensure that metabase has at least 2GB of RAM (defaults to starter)
    autoDeploy: false
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase:
          name: fishermantest
          property: connectionString
databases:
  - name: fishermantest
    databaseName: fishermantest
    ipAllowList: [] # only allow internal connections
